"""Behaviour preservation: reports must match those produced by the released v0.1.0.

The golden file was generated by scoreparity 0.1.0 itself (see tests/golden/make_golden.py).
A failure here means a change altered what users get for the same inputs and config.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

import pytest

import scoreparity as sp
from tests.golden.make_golden import CONFIG, scenario_frames, stable

GOLDEN_DIR = Path(__file__).resolve().parent / "golden"

GOLDEN = json.loads((GOLDEN_DIR / "reports-v0.1.0.json").read_text(encoding="utf-8"))


def _assert_same(expected: Any, actual: Any, path: str = "$") -> None:
    if isinstance(expected, float) and isinstance(actual, (float, int)):
        assert math.isclose(expected, actual, rel_tol=1e-9, abs_tol=1e-15), (path, expected, actual)
    elif isinstance(expected, dict):
        assert isinstance(actual, dict), path
        assert set(expected) == set(actual), (path, set(expected) ^ set(actual))
        for key in expected:
            _assert_same(expected[key], actual[key], f"{path}.{key}")
    elif isinstance(expected, list):
        assert isinstance(actual, list), path
        assert len(expected) == len(actual), (path, len(expected), len(actual))
        for i, (e, a) in enumerate(zip(expected, actual, strict=True)):
            _assert_same(e, a, f"{path}[{i}]")
    else:
        assert expected == actual, (path, expected, actual)


def test_golden_was_generated_by_a_release() -> None:
    assert GOLDEN["_generated_with"] == "0.1.0"


@pytest.mark.parametrize("scenario", ["noise", "drift", "broken"])
def test_reports_match_v0_1_0(scenario: str) -> None:
    ref, cand = scenario_frames()[scenario]
    doc = json.loads(sp.compare(ref, cand, sp.from_dict(CONFIG)).to_json())
    _assert_same(GOLDEN[scenario], stable(doc))
